---
 - name: Generate file hosts
   ansible.builtin.template:
     src: generate_hosts.j2
     dest: /etc/hosts
     mode: 0644

 - name: Add the PVE repository key
   ansible.builtin.get_url:
    url: https://enterprise.proxmox.com/debian/proxmox-release-bookworm.gpg
    dest: /etc/apt/trusted.gpg.d/proxmox-release-bookworm.gpg

 - name: Add PVE installer repository
   ansible.builtin.apt_repository:
     repo: deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription
     state: present

 - name: Apt-get update
   ansible.builtin.apt:
    update_cache: yes

 - name: Install curl
   ansible.builtin.apt:
    name:
      - curl

 
 - name: Install proxmox kernel
   ansible.builtin.apt:
    name: proxmox-default-kernel

 - name: Overriding network devices name
   ansible.builtin.template:
    src: generate_network_link.j2
    dest: /etc/systemd/network/10-{{item}}.link
    mode: 0775
   vars:
    active_interface: "{{ lookup('vars', 'ansible_' ~ item).macaddress }}"
   with_items: "{{ansible_interfaces}}"
   when: ansible_{{item}}.type == ether
   notify:
    - System reboot

 - name: Flush handlers
   meta: flush_handlers

 - name: Install PVE package
   ansible.builtin.apt:
    name:
      - proxmox-ve
      - postfix
      - open-iscsi
      - chrony

 - name: Remove default kernel
   shell: "apt remove -y linux-image-amd64 'linux-image-6.1*'"

 - name: Remove os-prober package
   ansible.builtin.apt:
    name: os-prober
    state: absent

 - name: Remove PVE installer repository
   ansible.builtin.file:
    path: /etc/apt/sources.list.d/pve-enterprise.list
    state: absent
