---
# tasks file for proxmox_installer
 - name: Generate file hosts
   ansible.builtin.template:
     src: hosts.j2
     dest: /etc/hosts
     mode: 0644
 
 - name: Add the Proxmox VE repository key
   ansible.builtin.get_url:
    url: https://enterprise.proxmox.com/debian/proxmox-release-bookworm.gpg
    dest: /etc/apt/trusted.gpg.d/proxmox-release-bookworm.gpg

 - name: Add repository
   ansible.builtin.apt_repository:
     repo: deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription
     state: present

 - name:  Apt-get update
   ansible.builtin.apt:
    update_cache: yes

 - name: Install proxmox-default-kernel
   ansible.builtin.apt:
    name: proxmox-default-kernel
 
 - name: Remove default kernel
   ansible.builtin.apt:
    name: linux-image-amd64 'linux-image-6.1*' 
    state: absent
 
 - name: Systemctl Reboot
   ansible.builtin.systemd_service:
    daemon_reload: true   

 - name: Proxmox Install
   ansible.builtin.apt:
    name:
      - proxmox-ve
      - postfix
      - chrony
      
 - name: Systemctl Reboot
   ansible.builtin.systemd_service:
    daemon_reload: true 
